"""initial

Revision ID: bcd59385275b
Revises: 
Create Date: 2026-01-20 02:47:46.847279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd59385275b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_courses_is_archived', 'courses', ['is_archived'], unique=False)
    op.create_index('ix_courses_major_archived', 'courses', ['major_id', 'is_archived'], unique=False)
    op.create_index('ix_courses_major_id', 'courses', ['major_id'], unique=False)
    op.create_index('ix_courses_name', 'courses', ['name'], unique=False)
    op.create_index('ix_reviews_course_id', 'reviews', ['course_id'], unique=False)
    op.create_index('ix_reviews_course_visible', 'reviews', ['course_id', 'is_hidden', 'created_at'], unique=False)
    op.create_index('ix_reviews_created_at', 'reviews', ['created_at'], unique=False)
    op.create_unique_constraint('uq_reviews_user_course', 'reviews', ['user_id', 'course_id'])
    op.create_index('ix_users_verification_token', 'users', ['verification_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_verification_token', table_name='users')
    op.drop_constraint('uq_reviews_user_course', 'reviews', type_='unique')
    op.drop_index('ix_reviews_created_at', table_name='reviews')
    op.drop_index('ix_reviews_course_visible', table_name='reviews')
    op.drop_index('ix_reviews_course_id', table_name='reviews')
    op.drop_index('ix_courses_name', table_name='courses')
    op.drop_index('ix_courses_major_id', table_name='courses')
    op.drop_index('ix_courses_major_archived', table_name='courses')
    op.drop_index('ix_courses_is_archived', table_name='courses')
    # ### end Alembic commands ###
